from __future__ import annotations

"""POWERHOUSE AI V74 — Maximum Move Capture & Accountability OS.

Additive orchestration over the V73 LTS / V72.2 cumulative intelligence stack.
Primary engineering objective:
MAXIMUM MOVE CAPTURE + EARLY DETECTION + HIGH-QUALITY EXECUTION + ZERO AVOIDABLE MISSES.

This module is read-only decision support. It never places orders and never claims
100% profitability or guaranteed movement capture. Missing/stale evidence stays visible.
"""

import json
import math
import os
import sqlite3
import statistics
import threading
import time
from collections import defaultdict, deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional
from zoneinfo import ZoneInfo

from v73_lts_engine import (
    build_v73,
    circuit_hunter,
    depth_dom_intelligence,
    hero_execution_plan as hero_execution_plan_v73,
    volume_pulse,
)

VERSION = "74.0"  # API compatibility
BUILD_VERSION = "74.2"
RELEASE = "74.2-autonomous-call-intelligence"
IST = ZoneInfo("Asia/Kolkata")
_LOCK = threading.RLock()

TOP_LEVEL_TABS = [
    "COMMAND", "LIVE MARKET", "RADAR", "PRE-MOVE", "HERO", "AUTO TRENDER",
    "BREAKOUT", "REVERSAL", "SUPPLY-DEMAND", "SECTORS", "HEATMAP",
    "GAINERS-LOSERS", "FAST MOVERS", "DERIVATIVES", "OPTION CHAIN", "OI",
    "FUTURES", "GREEKS", "IV", "EXPIRY", "VOLUME", "ORDER FLOW", "DEPTH",
    "SMART MONEY", "CHART", "PATTERNS", "CANDLESTICKS", "VIX", "CIRCUITS",
    "ALERTS", "RE-ENTRY", "MISSED MOVES", "REPLAY", "PERFORMANCE", "SYSTEM",
]
TAB_ARCHITECTURE = [
    {"id": t.lower().replace(" ", "-").replace("/", "-"), "label": t}
    for t in TOP_LEVEL_TABS
]

# V74.1 UI workspaces merge repetitive legacy pages while preserving the original
# 35 feature identifiers above for backward compatibility and API/test continuity.
WORKSPACE_ARCHITECTURE = [
    {"id":"command","label":"COMMAND","merges":["COMMAND"]},
    {"id":"market","label":"MARKET","merges":["LIVE MARKET","GAINERS-LOSERS","HEATMAP","VIX","SECTORS"]},
    {"id":"opportunities","label":"OPPORTUNITIES","merges":["RADAR","PRE-MOVE","AUTO TRENDER","BREAKOUT","REVERSAL","FAST MOVERS","CIRCUITS"]},
    {"id":"calls","label":"CALLS","merges":["HERO","RE-ENTRY","SUPPLY-DEMAND"]},
    {"id":"derivatives","label":"DERIVATIVES","merges":["DERIVATIVES","OPTION CHAIN","OI","FUTURES","GREEKS","IV","EXPIRY"]},
    {"id":"flow-technical","label":"FLOW & TECHNICAL","merges":["VOLUME","ORDER FLOW","DEPTH","SMART MONEY","CHART","PATTERNS","CANDLESTICKS","SUPPLY-DEMAND"]},
    {"id":"alerts","label":"ALERTS","merges":["ALERTS"]},
    {"id":"journal-audit","label":"JOURNAL & AUDIT","merges":["MISSED MOVES","REPLAY","PERFORMANCE"]},
    {"id":"system","label":"SYSTEM","merges":["SYSTEM"]},
]

LIFECYCLE = [
    "DISCOVERY", "EARLY CLUE", "BUILDING", "ACCELERATING", "ARMING",
    "TRIGGER NEAR", "TRIGGER READY", "HERO", "ENTRY ACTIVE", "T1", "T2",
    "T3", "RUNNER", "EXIT / RE-ENTRY",
]
MOVE_CLASSES = [
    "MICRO MOVE", "TRADEABLE MOVE", "BIG MOVE", "SECTOR MOVE",
    "BREAKOUT MOVE", "REVERSAL MOVE", "CIRCUIT MOVE", "EXPIRY GAMMA MOVE",
]
MISS_CLASSES = [
    "NOT DISCOVERED", "DISCOVERED LATE", "PROMOTION TOO SLOW",
    "OPTION CHAIN DELAY", "FEED STALE", "THRESHOLD TOO STRICT",
    "SECTOR FILTER BLOCKED", "PATTERN LATE", "UI DELAY",
    "PREMIUM RESPONSE LATE", "RATE LIMIT",
]

SCOUT_WEIGHTS = {
    "price": 0.20,
    "volume": 0.15,
    "oi": 0.15,
    "sector": 0.12,
    "order_flow": 0.14,
    "pattern": 0.12,
    "options": 0.12,
}

# Intraday, process-local telemetry. V72/V73 replay remains the durable forensic source.
_SYMBOL_HISTORY: Dict[str, deque] = defaultdict(lambda: deque(maxlen=300))
_CANDIDATE_STATE: Dict[str, dict] = {}
_MOVE_EVENTS: deque = deque(maxlen=1200)
_MISS_EVENTS: deque = deque(maxlen=600)
_UI_LATENCY: deque = deque(maxlen=200)
# V74-native alert stream. Alerts are generated by the continuous scanner, not by
# browser polling. State is process-local; V72/V73 durable forensics remain the
# source for post-restart historical replay.
_V74_ALERT_HISTORY: deque = deque(maxlen=1000)
_V74_ALERT_LAST_SIG: Dict[str, float] = {}
_V74_ALERT_STAGE: Dict[str, dict] = {}

# V74.2 call intelligence state. The SQLite journal survives process restarts when the
# configured runtime path survives; on ephemeral hosting it should be pointed to a
# persistent disk via POWERHOUSE_V74_DB_PATH for deploy-to-deploy durability.
ROOT = Path(__file__).parent
V74_DB_PATH = Path(os.getenv("POWERHOUSE_V74_DB_PATH") or (ROOT / ".runtime" / "powerhouse_v74_calls.sqlite3"))
_CALL_STATE: Dict[str, dict] = {}
_SHADOW_HISTORY: deque = deque(maxlen=1200)

_CALL_SCHEMA = """
CREATE TABLE IF NOT EXISTS v74_calls(
  call_id TEXT PRIMARY KEY, epoch REAL NOT NULL, updated_epoch REAL NOT NULL,
  symbol TEXT NOT NULL, action TEXT NOT NULL, status TEXT NOT NULL,
  entry_low REAL, ideal_entry REAL, entry_high REAL, sl REAL, structural_sl REAL,
  t1 REAL, t2 REAL, t3 REAL, extended_target REAL, premium REAL,
  quality_score REAL, rr_t1 REAL, stage TEXT, expiry TEXT, strike REAL,
  result TEXT, max_favorable_pct REAL DEFAULT 0, max_adverse_pct REAL DEFAULT 0,
  payload_json TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_v74_calls_epoch ON v74_calls(epoch DESC);
CREATE INDEX IF NOT EXISTS idx_v74_calls_symbol ON v74_calls(symbol, epoch DESC);
"""

def _call_db():
    V74_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    c = sqlite3.connect(V74_DB_PATH, timeout=8)
    c.row_factory = sqlite3.Row
    c.executescript(_CALL_SCHEMA)
    return c


def _f(v: Any, default: Optional[float] = None) -> Optional[float]:
    try:
        x = float(v)
        return x if math.isfinite(x) else default
    except Exception:
        return default


def _clamp(v: float, lo: float = 0.0, hi: float = 100.0) -> float:
    return max(lo, min(hi, float(v)))


def _symbol(row: dict) -> str:
    return str(row.get("symbol") or row.get("tradingsymbol") or "").upper().strip()


def _snapshot_rows(snapshot: dict, v73: Optional[dict] = None) -> List[dict]:
    """Prefer V72 pre-move rows; merge snapshot rows without inventing missing fields."""
    rows: List[dict] = []
    if isinstance(v73, dict):
        base72 = v73.get("base_v72") or {}
        pm = base72.get("pre_move_rows") or []
        if isinstance(pm, list):
            rows.extend(x for x in pm if isinstance(x, dict))
    for key in ("fno_universe", "stocks", "stock_rows", "sector_data", "sector_heatmap"):
        val = snapshot.get(key)
        if isinstance(val, list):
            rows.extend(x for x in val if isinstance(x, dict))
    ded: Dict[str, dict] = {}
    for r in rows:
        sym = _symbol(r)
        if not sym:
            continue
        ded[sym] = {**ded.get(sym, {}), **r, "symbol": sym}
    return list(ded.values())


def _quote_age(row: dict) -> Optional[float]:
    return _f(row.get("quote_age_sec"), _f(row.get("age_sec"), _f(row.get("feed_age_sec"))))


def _change_pct(row: dict) -> float:
    return _f(row.get("change_pct"), _f(row.get("changePercent"), 0.0)) or 0.0


def _history_metrics(sym: str, ltp: Optional[float], volume: Optional[float], oi: Optional[float]) -> dict:
    now = time.time()
    with _LOCK:
        h = _SYMBOL_HISTORY[sym]
        prior = h[-1] if h else None
        h.append({"t": now, "ltp": ltp, "volume": volume, "oi": oi})
        # A short baseline if API polling is slower than 15s; no interpolation/fake ticks.
        def ref(seconds: int) -> Optional[dict]:
            # Only use a genuinely old-enough sample. With the continuous scanner
            # running every few seconds, reusing a 3s sample as a synthetic 15s/30s/60s
            # reference would exaggerate velocity and create false early clues.
            target = now - seconds
            for item in reversed(h):
                if item["t"] <= target:
                    return item
            return None
        r15, r30, r60 = ref(15), ref(30), ref(60)

    def pct(old: Optional[float], cur: Optional[float]) -> Optional[float]:
        if old is None or cur is None or old == 0:
            return None
        return (cur - old) / abs(old) * 100.0

    p15 = pct(_f((r15 or {}).get("ltp")), ltp)
    p30 = pct(_f((r30 or {}).get("ltp")), ltp)
    p60 = pct(_f((r60 or {}).get("ltp")), ltp)
    v60 = pct(_f((r60 or {}).get("volume")), volume)
    oi60 = pct(_f((r60 or {}).get("oi")), oi)
    acceleration = None
    if p15 is not None and p30 is not None:
        acceleration = p15 - (p30 / 2.0)
    return {
        "price_15s_pct": p15,
        "price_30s_pct": p30,
        "price_60s_pct": p60,
        "price_acceleration": acceleration,
        "volume_60s_pct": v60,
        "oi_60s_pct": oi60,
        "samples": len(_SYMBOL_HISTORY.get(sym, ())),
        "prior": prior,
    }


def _score_price(row: dict, hm: dict) -> dict:
    chg = abs(_change_pct(row))
    p15, p30, p60 = (_f(hm.get(k)) for k in ("price_15s_pct", "price_30s_pct", "price_60s_pct"))
    accel = abs(_f(hm.get("price_acceleration"), 0.0) or 0.0)
    live_parts = [abs(x) for x in (p15, p30, p60) if x is not None]
    score = _clamp(chg * 13 + (max(live_parts) * 38 if live_parts else 0) + accel * 55)
    ready = _f(row.get("ltp")) is not None
    return {"status": "READY" if ready else "UNAVAILABLE", "score": round(score, 1) if ready else None,
            "change_pct": round(_change_pct(row), 3), "velocity": {"15s": p15, "30s": p30, "60s": p60},
            "acceleration": _f(hm.get("price_acceleration"))}


def _score_volume(row: dict, hm: dict) -> dict:
    vp = volume_pulse(row)
    if vp.get("status") != "READY":
        return {"status": "UNAVAILABLE", "score": None, "rvol": None, "volume_velocity": _f(hm.get("volume_60s_pct"))}
    rvol = _f(vp.get("rvol"))
    vv = abs(_f(hm.get("volume_60s_pct"), 0.0) or 0.0)
    base = _f(vp.get("score"), 0.0) or 0.0
    score = _clamp(base * 0.75 + min(25, vv * 0.8))
    return {"status": "READY", "score": round(score, 1), "rvol": rvol,
            "volume_velocity": _f(hm.get("volume_60s_pct")), "state": vp.get("state"),
            "turnover": vp.get("turnover_estimate")}


def _oi_value(row: dict) -> Optional[float]:
    return _f(row.get("futures_oi"), _f(row.get("oi"), _f(row.get("open_interest"))))


def _score_oi(row: dict, hm: dict) -> dict:
    d = _f(row.get("futures_oi_change_pct"), _f(row.get("oi_change_pct"), _f(row.get("delta_oi_pct"))))
    vel = _f(row.get("oi_velocity"), _f(hm.get("oi_60s_pct")))
    acc = _f(row.get("oi_acceleration"))
    state = row.get("oi_state")
    ready = any(x is not None for x in (d, vel, acc)) or bool(state)
    if not ready:
        return {"status": "UNAVAILABLE", "score": None, "delta_oi_pct": None, "oi_velocity": None, "oi_acceleration": None}
    score = _clamp(abs(d or 0) * 8 + abs(vel or 0) * 2.2 + abs(acc or 0) * 1.8 + (12 if state else 0))
    return {"status": "READY", "score": round(score, 1), "delta_oi_pct": d, "oi_velocity": vel,
            "oi_acceleration": acc, "state": state}


def _score_sector(row: dict) -> dict:
    strength = _f(row.get("sector_strength"), _f(row.get("sector_score"), _f(row.get("sector_momentum"))))
    breadth = _f(row.get("sector_breadth"), _f(row.get("breadth_pct")))
    ignition = row.get("sector_ignition")
    ready = strength is not None or breadth is not None or ignition is not None
    if not ready:
        return {"status": "UNAVAILABLE", "score": None, "strength": None, "breadth": None, "ignition": None}
    # Strength values may already be 0..100; small signed values are treated as percentage momentum.
    s = 50.0
    if strength is not None:
        s = strength if 0 <= strength <= 100 else _clamp(50 + strength * 10)
    if breadth is not None:
        b = breadth if 0 <= breadth <= 100 else _clamp(50 + breadth)
        s = s * 0.65 + b * 0.35
    if bool(ignition):
        s = min(100, s + 12)
    return {"status": "READY", "score": round(_clamp(s), 1), "strength": strength, "breadth": breadth,
            "ignition": bool(ignition), "sector": row.get("sector")}


def _score_order_flow(row: dict) -> dict:
    dom = row.get("depth_intelligence") or depth_dom_intelligence(row)
    if dom.get("status") != "READY":
        return {"status": "UNAVAILABLE", "score": None, "pressure": None, "spread_pct": None}
    pressure = _f(dom.get("pressure"))
    spread = _f(dom.get("spread_pct"))
    side = str(row.get("v72_side") or row.get("side") or "").upper()
    directional = pressure
    if pressure is not None and side in ("PE", "PUT", "SELL", "SHORT"):
        directional = 100 - pressure
    score = _clamp((directional if directional is not None else 50) - max(0, (spread or 0.8) - 0.8) * 12)
    absorption = row.get("absorption") or row.get("depth_absorption")
    vacuum = row.get("liquidity_vacuum")
    if absorption:
        score = min(100, score + 7)
    if vacuum:
        score = min(100, score + 8)
    return {"status": "READY", "score": round(score, 1), "pressure": pressure, "spread_pct": spread,
            "bias": dom.get("bias"), "absorption": absorption, "liquidity_vacuum": vacuum,
            "bid_refill": row.get("bid_refill"), "ask_depletion": row.get("ask_depletion")}


def _pattern_name(row: dict) -> Optional[str]:
    p = row.get("pattern") or row.get("developing_pattern") or row.get("pattern_name")
    if p:
        return str(p)
    arr = row.get("forming_patterns")
    if isinstance(arr, list) and arr:
        x = arr[0]
        if isinstance(x, dict):
            return str(x.get("name") or x.get("pattern") or "") or None
        return str(x)
    return None


def _score_pattern(row: dict) -> dict:
    pattern = _pattern_name(row)
    quality = _f(row.get("pattern_quality"), _f(row.get("formation_quality")))
    location = _f(row.get("location_score"))
    breakout = bool(row.get("breakout") or row.get("breakout_ready") or "BREAK" in str(pattern or "").upper())
    reversal = bool(row.get("reversal") or "REVERS" in str(pattern or "").upper())
    compression = bool(row.get("compression") or "SQUEEZE" in str(pattern or "").upper())
    ready = pattern is not None or quality is not None or any((breakout, reversal, compression))
    if not ready:
        return {"status": "UNAVAILABLE", "score": None, "pattern": None}
    score = quality if quality is not None else 48.0
    if location is not None:
        score = score * 0.72 + location * 0.28
    score += 8 if breakout or reversal else 4 if compression else 0
    return {"status": "READY", "score": round(_clamp(score), 1), "pattern": pattern,
            "breakout": breakout, "reversal": reversal, "compression": compression,
            "location_score": location}


def _score_options(row: dict) -> dict:
    premium = _f(row.get("premium_response"), _f((row.get("scores") or {}).get("premium_response")))
    iv = _f(row.get("iv"), _f(row.get("implied_volatility")))
    gamma = _f(row.get("gamma"), _f((row.get("scores") or {}).get("gamma")))
    wall = row.get("oi_wall_migration") or row.get("strike_migration")
    elasticity = _f(row.get("premium_elasticity"))
    ready = any(x is not None for x in (premium, iv, gamma, elasticity)) or wall is not None
    if not ready:
        return {"status": "UNAVAILABLE", "score": None, "premium_response": None, "iv": None,
                "gamma": None, "oi_wall_migration": None}
    vals = []
    if premium is not None:
        vals.append(_clamp(premium))
    if gamma is not None:
        vals.append(_clamp(gamma if 0 <= gamma <= 100 else gamma * 1000))
    if elasticity is not None:
        vals.append(_clamp(50 + elasticity * 12))
    if wall is not None:
        vals.append(68.0)
    score = statistics.fmean(vals) if vals else 50.0
    return {"status": "READY", "score": round(_clamp(score), 1), "premium_response": premium,
            "iv": iv, "gamma": gamma, "oi_wall_migration": wall, "premium_elasticity": elasticity,
            "premium_failure": row.get("premium_failure")}


def seven_scouts(row: dict) -> dict:
    sym = _symbol(row)
    ltp = _f(row.get("ltp"))
    vol = _f(row.get("volume"))
    oi = _oi_value(row)
    hm = _history_metrics(sym, ltp, vol, oi) if sym else {}
    scouts = {
        "price": _score_price(row, hm),
        "volume": _score_volume(row, hm),
        "oi": _score_oi(row, hm),
        "sector": _score_sector(row),
        "order_flow": _score_order_flow(row),
        "pattern": _score_pattern(row),
        "options": _score_options(row),
    }
    weighted = 0.0
    used = 0.0
    ready = []
    for name, info in scouts.items():
        score = _f(info.get("score"))
        if info.get("status") == "READY" and score is not None:
            w = SCOUT_WEIGHTS[name]
            weighted += score * w
            used += w
            ready.append(name)
    aggregate = weighted / used if used else 0.0
    return {
        "symbol": sym,
        "aggregate_score": round(_clamp(aggregate), 1),
        "ready_scouts": ready,
        "ready_count": len(ready),
        "missing_scouts": [k for k in scouts if k not in ready],
        "scouts": scouts,
        "history_metrics": {k: v for k, v in hm.items() if k != "prior"},
    }


def _lifecycle(score: float, row: dict, scout: dict) -> str:
    # Preserve stronger evidence-supported V72 state when available.
    base = str(row.get("pre_move_stage") or row.get("stage") or "").upper().strip()
    aliases = {
        "SCANNING": "DISCOVERY", "WATCH": "EARLY CLUE", "EARLY MOVER": "EARLY CLUE",
        "EARLY CLUE": "EARLY CLUE", "BUILDING": "BUILDING", "ACCELERATING": "ACCELERATING",
        "ARMING": "ARMING", "TRIGGER NEAR": "TRIGGER NEAR", "TRIGGER READY": "TRIGGER READY",
        "HERO READY": "HERO", "HERO ACTIVE": "ENTRY ACTIVE",
    }
    by_score = (
        "TRIGGER READY" if score >= 84 else
        "TRIGGER NEAR" if score >= 76 else
        "ARMING" if score >= 67 else
        "ACCELERATING" if score >= 57 else
        "BUILDING" if score >= 45 else
        "EARLY CLUE" if score >= 32 else
        "DISCOVERY"
    )
    b = aliases.get(base)
    if not b:
        return by_score
    rank = {x: i for i, x in enumerate(LIFECYCLE)}
    return b if rank.get(b, -1) > rank.get(by_score, -1) else by_score


def _sticky_lifecycle(sym: str, current: str) -> tuple[str, bool, Optional[str]]:
    """Keep a recently reached discovery stage visible long enough for UI/audit.

    This is discovery hysteresis only; Hero performs a fresh strict qualification.
    A transient weak snapshot therefore cannot erase an early clue before the 15s UI
    poll sees it, while stale stages automatically expire.
    """
    if not sym or current not in LIFECYCLE:
        return current, False, None
    now = time.time()
    rank = {x: i for i, x in enumerate(LIFECYCLE)}
    with _LOCK:
        old = _CANDIDATE_STATE.get(sym) or {}
        peak = str(old.get("peak_stage") or "")
        peak_at = _f(old.get("peak_stage_at"))
    if peak not in rank or peak_at is None:
        return current, False, None
    # Preserve BUILDING/ACCELERATING for 30s and ARMING+ for 60s.
    ttl = 60.0 if rank[peak] >= rank["ARMING"] else 30.0
    age = now - peak_at
    if age <= ttl and rank[peak] > rank[current]:
        return peak, True, current
    return current, False, None


def _move_class(row: dict, scout: dict, session: Optional[dict] = None) -> str:
    # Discovery must react to the move that is happening now, not only to the
    # stock's change from previous close. Short-window velocities come from real
    # scanner samples and are deliberately broader than Hero qualification.
    chg = abs(_change_pct(row))
    hm = scout.get("history_metrics") or {}
    p15 = abs(_f(hm.get("price_15s_pct"), 0.0) or 0.0)
    p30 = abs(_f(hm.get("price_30s_pct"), 0.0) or 0.0)
    p60 = abs(_f(hm.get("price_60s_pct"), 0.0) or 0.0)
    short_move = max(p15, p30, p60)
    p = scout.get("scouts", {}).get("pattern", {})
    s = scout.get("scouts", {}).get("sector", {})
    options = scout.get("scouts", {}).get("options", {})
    ltp = _f(row.get("ltp"))
    uc = _f(row.get("upper_circuit_limit"), _f(row.get("upper_circuit"), _f(row.get("uc"))))
    lc = _f(row.get("lower_circuit_limit"), _f(row.get("lower_circuit"), _f(row.get("lc"))))
    if ltp is not None and ((uc and abs(uc-ltp)/max(abs(ltp),1e-9) <= 0.003) or (lc and abs(ltp-lc)/max(abs(ltp),1e-9) <= 0.003)):
        return "CIRCUIT MOVE"
    if (session or {}).get("expiry_mode") and (_f(options.get("gamma"), 0) or 0) >= 65:
        return "EXPIRY GAMMA MOVE"
    if p.get("reversal") and (chg >= 0.45 or short_move >= 0.18):
        return "REVERSAL MOVE"
    if p.get("breakout") and (chg >= 0.45 or short_move >= 0.18):
        return "BREAKOUT MOVE"
    if s.get("ignition") and (_f(s.get("score"), 0) or 0) >= 70 and (chg >= 0.55 or short_move >= 0.20):
        return "SECTOR MOVE"
    if chg >= 2.0 or p60 >= 0.75 or p30 >= 0.55:
        return "BIG MOVE"
    if chg >= 0.75 or p60 >= 0.28 or p30 >= 0.18 or p15 >= 0.10:
        return "TRADEABLE MOVE"
    return "MICRO MOVE"


def _direction(row: dict) -> str:
    side = str(row.get("v72_side") or row.get("side") or "").upper()
    if side in ("CE", "CALL", "BUY", "LONG", "BULLISH"):
        return "UP"
    if side in ("PE", "PUT", "SELL", "SHORT", "BEARISH"):
        return "DOWN"
    return "UP" if _change_pct(row) >= 0 else "DOWN"


def _second_chance(row: dict, scout: dict, stage: str) -> List[str]:
    out: List[str] = []
    if row.get("breakout_retest") or row.get("retest"):
        out.append("Breakout Retest")
    if row.get("vwap_reclaim"):
        out.append("VWAP Reclaim")
    if row.get("demand_retest"):
        out.append("Demand Retest")
    if row.get("supply_flip"):
        out.append("Supply Flip")
    if row.get("pullback_continuation"):
        out.append("Pullback Continuation")
    if row.get("ema_hold") or row.get("vwap_hold"):
        out.append("EMA/VWAP Hold")
    opt = scout.get("scouts", {}).get("options", {})
    if (_f(opt.get("premium_response"), 0) or 0) >= 65 and stage not in ("DISCOVERY", "EARLY CLUE"):
        out.append("Option Premium Re-acceleration")
    if row.get("alternate_strike_ready"):
        out.append("Alternate Strike")
    if row.get("reentry_ready"):
        out.append("Re-entry")
    # Do not fabricate a retest; if no evidence is supplied, state what is being watched.
    if not out and stage in ("TRIGGER READY", "HERO", "ENTRY ACTIVE"):
        out = ["WATCH: Breakout Retest", "WATCH: VWAP/EMA Hold", "WATCH: Re-entry"]
    return out


def _big_move_state(move_class: str, score: float, scout: dict) -> str:
    if move_class != "MICRO MOVE" and abs(_f(scout.get("scouts", {}).get("price", {}).get("change_pct"), 0) or 0) >= 0.75:
        return "MOVE ACTIVE"
    if score >= 78:
        return "BREAK IMMINENT"
    if score >= 65:
        return "PRESSURE RISING"
    if score >= 48:
        return "EARLY BUILD"
    return "WATCH"


def _session_name(now: Optional[datetime] = None) -> str:
    now = now or datetime.now(IST)
    hm = now.hour * 60 + now.minute
    if 9 * 60 + 15 <= hm <= 9 * 60 + 30:
        return "OPENING BRAIN"
    if 14 * 60 + 45 <= hm <= 15 * 60 + 30:
        return "CLOSING BRAIN"
    if 9 * 60 + 15 <= hm <= 15 * 60 + 30:
        return "INTRADAY BRAIN"
    return "MARKET CLOSED / OFF SESSION"


def _expiry_mode(snapshot: dict, v73: Optional[dict] = None) -> bool:
    flags = [
        snapshot.get("expiry_mode"), snapshot.get("is_expiry_day"), snapshot.get("hero_zero_mode"),
        ((v73 or {}).get("base_v72") or {}).get("expiry_mode"),
        (((v73 or {}).get("base_v72") or {}).get("expiry_intelligence") or {}).get("is_expiry"),
    ]
    if any(x is True for x in flags):
        return True
    dte = _f(snapshot.get("days_to_expiry"))
    return dte == 0 if dte is not None else False


def session_brain(snapshot: dict, candidates: Optional[List[dict]] = None, v73: Optional[dict] = None) -> dict:
    now = datetime.now(IST)
    mode = _session_name(now)
    expiry = _expiry_mode(snapshot, v73)
    rows = candidates or []
    opening = sorted(rows, key=lambda x: (
        _f(((x.get("scout_pack") or {}).get("scouts") or {}).get("volume", {}).get("score"), 0) or 0,
        _f(x.get("score"), 0) or 0,
    ), reverse=True)[:15]
    closing = sorted(rows, key=lambda x: (
        abs(_f(x.get("change_pct"), 0) or 0), _f(x.get("score"), 0) or 0
    ), reverse=True)[:15]
    return {
        "time_ist": now.isoformat(),
        "active_brain": "EXPIRY BRAIN" if expiry else mode,
        "expiry_mode": expiry,
        "opening_window": "09:15-09:30 IST",
        "closing_window": "14:45-15:30 IST",
        "opening_focus": ["gap", "opening volume", "opening range", "VWAP", "sector leadership", "first breakout", "first failure"],
        "closing_focus": ["short covering", "long unwinding", "closing momentum", "expiry pressure", "overnight risk"],
        "expiry_focus": ["gamma", "theta", "pinning", "wall migration", "premium decay", "Hero-Zero mode", "late-entry block"],
        "opening_candidates": opening,
        "closing_candidates": closing,
    }


def record_ui_latency(fetch_ms: Optional[float], render_ms: Optional[float], tab: Optional[str] = None) -> dict:
    item = {"t": time.time(), "fetch_ms": _f(fetch_ms), "render_ms": _f(render_ms), "tab": str(tab or "")[:40]}
    with _LOCK:
        _UI_LATENCY.append(item)
    return {"recorded": True, **item}


def _ui_delay_active() -> bool:
    with _LOCK:
        recent = list(_UI_LATENCY)[-30:]
    vals = [(_f(x.get("fetch_ms"), 0) or 0) + (_f(x.get("render_ms"), 0) or 0) for x in recent]
    return bool(vals and statistics.fmean(vals) >= 1800)


def _root_cause(row: dict, candidate: Optional[dict], moved: bool) -> Optional[str]:
    if not moved:
        return None
    age = _quote_age(row)
    if age is not None and age > 10:
        return "FEED STALE"
    error = str(row.get("provider_error") or row.get("error") or "").lower()
    if "rate limit" in error or "429" in error:
        return "RATE LIMIT"
    if _ui_delay_active():
        return "UI DELAY"
    if candidate is None:
        return "NOT DISCOVERED"
    if candidate.get("discovered_after_move"):
        return "DISCOVERED LATE"
    if candidate.get("promotion_lag_sec") and (_f(candidate.get("promotion_lag_sec"), 0) or 0) > 45:
        return "PROMOTION TOO SLOW"
    sc = candidate.get("scout_pack") or {}
    opts = (sc.get("scouts") or {}).get("options") or {}
    if opts.get("status") != "READY" and row.get("option_chain_expected"):
        return "OPTION CHAIN DELAY"
    sector = (sc.get("scouts") or {}).get("sector") or {}
    if sector.get("status") == "READY" and (_f(sector.get("score"), 50) or 50) < 40:
        return "SECTOR FILTER BLOCKED"
    pattern = (sc.get("scouts") or {}).get("pattern") or {}
    if pattern.get("status") != "READY" and row.get("pattern_expected"):
        return "PATTERN LATE"
    premium = _f(opts.get("premium_response"))
    if opts.get("status") == "READY" and premium is not None and premium < 45:
        return "PREMIUM RESPONSE LATE"
    if (_f(candidate.get("score"), 0) or 0) < 45:
        return "THRESHOLD TOO STRICT"
    return "DISCOVERED LATE"


def _remember_candidate(row: dict, candidate: dict) -> None:
    sym = candidate["symbol"]
    if not sym:
        return
    now = time.time()
    ltp = _f(row.get("ltp"))
    side = _direction(row)
    with _LOCK:
        old = _CANDIDATE_STATE.get(sym)
        if old is None:
            old = {
                "symbol": sym, "first_seen": now, "first_ltp": ltp, "side": side,
                "first_stage": candidate.get("stage"), "first_score": candidate.get("score"),
                "max_stage_rank": LIFECYCLE.index(candidate.get("stage")) if candidate.get("stage") in LIFECYCLE else 0,
                "peak_stage": candidate.get("stage"), "peak_stage_at": now,
                "mfe_pct": 0.0, "mae_pct": 0.0, "move_started_at": None,
                "first_clue_at": now if candidate.get("stage") != "DISCOVERY" else None,
                "trigger_ready_at": now if candidate.get("stage") == "TRIGGER READY" else None,
            }
            _CANDIDATE_STATE[sym] = old
        rank = LIFECYCLE.index(candidate.get("stage")) if candidate.get("stage") in LIFECYCLE else 0
        if rank > int(old.get("max_stage_rank") or 0):
            old["max_stage_rank"] = rank
            old["peak_stage"] = candidate.get("stage")
            old["peak_stage_at"] = now
        elif rank == int(old.get("max_stage_rank") or 0) and candidate.get("stage") == old.get("peak_stage"):
            # Refresh the peak timestamp only while the evidence is genuinely still at that stage.
            old["peak_stage_at"] = now
        if old.get("first_clue_at") is None and candidate.get("stage") != "DISCOVERY":
            old["first_clue_at"] = now
        if old.get("trigger_ready_at") is None and candidate.get("stage") == "TRIGGER READY":
            old["trigger_ready_at"] = now
        if old.get("first_ltp") and ltp:
            raw = (ltp - old["first_ltp"]) / abs(old["first_ltp"]) * 100.0
            fav = raw if old.get("side") == "UP" else -raw
            old["mfe_pct"] = max(_f(old.get("mfe_pct"), 0) or 0, fav)
            old["mae_pct"] = min(_f(old.get("mae_pct"), 0) or 0, fav)
        old["latest"] = candidate
        old["last_seen"] = now


def _audit_move(row: dict, candidate: dict) -> Optional[dict]:
    move_class = candidate.get("move_class")
    if move_class == "MICRO MOVE":
        return None
    sym = candidate.get("symbol")
    now = time.time()
    with _LOCK:
        state = _CANDIDATE_STATE.get(sym)
        existing = next((x for x in reversed(_MOVE_EVENTS) if x.get("symbol") == sym and now - x.get("event_at", 0) < 900), None)
        if existing:
            existing["move_class"] = move_class
            existing["latest_change_pct"] = candidate.get("change_pct")
            return existing
        first_clue = (state or {}).get("first_clue_at")
        event = {
            "symbol": sym,
            "event_at": now,
            "move_class": move_class,
            "direction": _direction(row),
            "latest_change_pct": candidate.get("change_pct"),
            "first_clue_at": first_clue,
            "lead_time_sec": round(now - first_clue, 2) if first_clue and first_clue <= now else None,
            "detection": "EARLY" if first_clue and first_clue < now - 1 else "LATE",
        }
        _MOVE_EVENTS.append(event)
        cause = _root_cause(row, candidate if first_clue else None, True)
        if cause:
            miss = {**event, "classification": cause, "silent_miss": False}
            _MISS_EVENTS.append(miss)
            event["miss_classification"] = cause
        return event


def candidate_from_row(row: dict, session: Optional[dict] = None) -> dict:
    sc = seven_scouts(row)
    score = _f(sc.get("aggregate_score"), 0.0) or 0.0
    raw_stage = _lifecycle(score, row, sc)
    stage, stage_persisted, current_stage = _sticky_lifecycle(_symbol(row), raw_stage)
    move_class = _move_class(row, sc, session)
    cand = {
        "symbol": _symbol(row),
        "ltp": _f(row.get("ltp")),
        "change_pct": round(_change_pct(row), 3),
        "side": _direction(row),
        "score": round(score, 1),
        "stage": stage,
        "current_stage": current_stage or raw_stage,
        "stage_persisted": stage_persisted,
        "big_move_state": _big_move_state(move_class, score, sc),
        "move_class": move_class,
        "meaningful_move": move_class != "MICRO MOVE",
        "quote_age_sec": _quote_age(row),
        "scout_pack": sc,
        "second_chance": _second_chance(row, sc, stage),
        "sector": row.get("sector"),
        "pattern": _pattern_name(row),
        "vix_regime": row.get("vix_regime"),
        "supply_demand": row.get("supply_demand") or {
            "supply": row.get("supply_zone"), "demand": row.get("demand_zone")
        },
        "break_pressure": row.get("break_pressure"),
        "data_truth": {
            "fresh": (_quote_age(row) is None or (_quote_age(row) or 999) <= 10),
            "ready_scouts": sc.get("ready_count"),
            "missing_scouts": sc.get("missing_scouts"),
        },
    }
    _remember_candidate(row, cand)
    _audit_move(row, cand)
    return cand


def _coverage(v73: dict, candidates: List[dict]) -> dict:
    c = v73.get("opportunity_coverage") or {}
    expected = int(c.get("expected") or c.get("expected_universe") or 0)
    observed = int(c.get("observed") or len(candidates))
    fresh = int(c.get("fresh_under_10s") or sum(1 for x in candidates if (x.get("data_truth") or {}).get("fresh")))
    with _LOCK:
        moves = list(_MOVE_EVENTS)
        misses = list(_MISS_EVENTS)
    early = sum(1 for x in moves if x.get("detection") == "EARLY")
    late = sum(1 for x in moves if x.get("detection") == "LATE")
    miss_symbols = {x.get("symbol") for x in misses if x.get("classification") in ("NOT DISCOVERED", "FEED STALE", "RATE LIMIT")}
    leads = [_f(x.get("lead_time_sec")) for x in moves if _f(x.get("lead_time_sec")) is not None]
    return {
        "universe_expected": expected,
        "universe_covered": observed,
        "universe_coverage_pct": round(100 * observed / expected, 1) if expected else (100.0 if observed else 0.0),
        "fresh_quotes": fresh,
        "symbols_scanned": len(candidates),
        "meaningful_moves_today": len(moves),
        "moves_detected_early": early,
        "moves_detected_late": late,
        "moves_completely_missed": len(miss_symbols),
        "average_lead_time_sec": round(statistics.fmean(leads), 2) if leads else None,
        "coverage_state": c.get("coverage_state") or ("FULL" if expected and observed >= expected else "PARTIAL" if observed else "WARMING"),
        "silent_misses_allowed": False,
        "accountability": "Every observed meaningful move must be detected or receive an explicit miss classification.",
    }


def miss_killer_report(limit: int = 200) -> dict:
    with _LOCK:
        items = list(_MISS_EVENTS)[-max(1, min(limit, 1000)):]
    counts = {k: 0 for k in MISS_CLASSES}
    for x in items:
        k = str(x.get("classification") or "")
        if k in counts:
            counts[k] += 1
    repeated = sorted(({"classification": k, "count": v} for k, v in counts.items() if v), key=lambda x: x["count"], reverse=True)
    return {
        "version": VERSION,
        "allowed_classifications": MISS_CLASSES,
        "counts": counts,
        "repeated_problems": repeated,
        "events": list(reversed(items)),
        "silent_miss_allowed": False,
    }


def performance_intelligence(candidates: Optional[List[dict]] = None) -> dict:
    with _LOCK:
        states = list(_CANDIDATE_STATE.values())
        moves = list(_MOVE_EVENTS)
    grouped: Dict[str, List[dict]] = defaultdict(list)
    for st in states:
        latest = st.get("latest") or {}
        key = str(latest.get("pattern") or "NO_PATTERN")
        grouped[key].append(st)
    pattern_stats = []
    for pattern, rows in grouped.items():
        mfes = [_f(x.get("mfe_pct"), 0) or 0 for x in rows]
        maes = [_f(x.get("mae_pct"), 0) or 0 for x in rows]
        follow = sum(1 for x in mfes if x >= 0.75)
        pattern_stats.append({
            "pattern": pattern,
            "sample_size": len(rows),
            "observed_follow_through_pct": round(100 * follow / len(rows), 1) if rows else None,
            "median_mfe_pct": round(statistics.median(mfes), 3) if mfes else None,
            "median_mae_pct": round(statistics.median(maes), 3) if maes else None,
            "win_probability": None,
            "truth": "Observed follow-through only; not a forecast probability.",
        })
    pattern_stats.sort(key=lambda x: (x["sample_size"], x.get("observed_follow_through_pct") or 0), reverse=True)
    leads = [_f(x.get("lead_time_sec")) for x in moves if _f(x.get("lead_time_sec")) is not None]
    return {
        "version": VERSION,
        "pattern_records": pattern_stats[:100],
        "overall": {
            "tracked_setups": len(states),
            "meaningful_moves": len(moves),
            "median_lead_time_sec": round(statistics.median(leads), 2) if leads else None,
        },
        "dimensions": ["Pattern", "Regime", "Session", "Sector", "Entry type", "Strike quality", "Observed follow-through", "MFE", "MAE", "Average R", "False breakout rate", "Median lead time", "Sample size"],
        "policy": "No probability label is emitted from small or synthetic samples. Statistics are descriptive observations only.",
    }



def _alert_priority(candidate: dict) -> tuple[Optional[str], Optional[str]]:
    """Map a discovery state to an attention priority without implying profit odds."""
    stage = str(candidate.get("stage") or "DISCOVERY").upper()
    big = str(candidate.get("big_move_state") or "WATCH").upper()
    move_class = str(candidate.get("move_class") or "MICRO MOVE").upper()
    score = _f(candidate.get("score"), 0.0) or 0.0
    if stage in ("TRIGGER READY", "HERO", "ENTRY ACTIVE") or big in ("BREAK IMMINENT", "MOVE ACTIVE"):
        return "P0", "ACTIONABLE_STATE"
    if stage in ("ARMING", "TRIGGER NEAR") or move_class in ("BIG MOVE", "BREAKOUT MOVE", "REVERSAL MOVE", "SECTOR MOVE", "CIRCUIT MOVE", "EXPIRY GAMMA MOVE"):
        return "P1", "MOVE_PRESSURE"
    if stage in ("BUILDING", "ACCELERATING"):
        return "P2", "EARLY_BUILD"
    if stage == "EARLY CLUE" and score >= 32:
        return "P3", "EARLY_CLUE"
    return None, None


def _emit_v74_alert(priority: str, kind: str, candidate: dict, reason: str, ttl: int = 25) -> Optional[dict]:
    sym = str(candidate.get("symbol") or "").upper()
    if not sym:
        return None
    now = time.time()
    stage = str(candidate.get("stage") or "")
    big = str(candidate.get("big_move_state") or "")
    sig = f"{priority}|{kind}|{sym}|{stage}|{big}|{reason}"
    with _LOCK:
        if now - float(_V74_ALERT_LAST_SIG.get(sig) or 0.0) < max(5, int(ttl)):
            return None
        _V74_ALERT_LAST_SIG[sig] = now
        item = {
            "id": f"V74-{int(now*1000)}-{len(_V74_ALERT_HISTORY)}",
            "epoch": now,
            "priority": priority,
            "kind": kind,
            "symbol": sym,
            "title": f"{sym} {stage or big}",
            "reason": reason,
            "stage": stage,
            "big_move_state": big,
            "move_class": candidate.get("move_class"),
            "score": candidate.get("score"),
            "side": candidate.get("side"),
            "ltp": candidate.get("ltp"),
            "change_pct": candidate.get("change_pct"),
            "ready_scouts": ((candidate.get("scout_pack") or {}).get("ready_count")),
            "second_chance": candidate.get("second_chance") or [],
            "read_only": True,
        }
        _V74_ALERT_HISTORY.append(item)
        return item


def alert_engine_v74(candidates: List[dict], legacy_alerts: Optional[dict] = None) -> dict:
    """State-transition alerts generated on every server-side scan.

    Discovery alerts are broader than Hero qualification so a candidate can be surfaced
    early without pretending it is already a trade. Repeated identical states are
    deduplicated; promotions and important move-state changes are emitted immediately.
    """
    now = time.time()
    rank = {x: i for i, x in enumerate(LIFECYCLE)}
    fresh: List[dict] = []
    for c in candidates:
        sym = str(c.get("symbol") or "").upper()
        if not sym:
            continue
        stage = str(c.get("stage") or "DISCOVERY").upper()
        stage_rank = rank.get(stage, 0)
        big = str(c.get("big_move_state") or "WATCH").upper()
        priority, kind = _alert_priority(c)
        with _LOCK:
            prev = dict(_V74_ALERT_STAGE.get(sym) or {})
        prev_rank = int(prev.get("stage_rank") or 0)
        prev_big = str(prev.get("big_move_state") or "WATCH").upper()
        prev_meaningful = bool(prev.get("meaningful_move"))
        meaningful = bool(c.get("meaningful_move"))
        reason = None
        if priority:
            if not prev:
                # Do not dump hundreds of low-priority alerts on process warm-up.
                # Strong states present at startup are still surfaced.
                if priority in ("P0", "P1"):
                    reason = "scanner warm-start found high-priority state"
            elif stage_rank > prev_rank:
                reason = f"lifecycle promoted {prev.get('stage') or 'DISCOVERY'} → {stage}"
            elif big != prev_big and big in ("EARLY BUILD", "PRESSURE RISING", "BREAK IMMINENT", "MOVE ACTIVE"):
                reason = f"big-move state changed {prev_big} → {big}"
            elif meaningful and not prev_meaningful:
                reason = f"meaningful move detected: {c.get('move_class')}"
            elif (c.get("second_chance") or []) and not (prev.get("second_chance") or []):
                reason = "second-chance/re-entry evidence appeared"
        if reason and priority and kind:
            ttl = 15 if priority == "P0" else 25 if priority == "P1" else 45 if priority == "P2" else 75
            item = _emit_v74_alert(priority, kind, c, reason, ttl)
            if item:
                fresh.append(item)
        with _LOCK:
            _V74_ALERT_STAGE[sym] = {
                "stage": stage,
                "stage_rank": stage_rank,
                "big_move_state": big,
                "meaningful_move": meaningful,
                "second_chance": list(c.get("second_chance") or []),
                "last_seen": now,
            }
    # Keep state bounded to names observed within a trading-session scale window.
    with _LOCK:
        for sym in list(_V74_ALERT_STAGE):
            if now - float((_V74_ALERT_STAGE.get(sym) or {}).get("last_seen") or now) > 86400:
                _V74_ALERT_STAGE.pop(sym, None)
        own = list(_V74_ALERT_HISTORY)
    legacy_items = list((legacy_alerts or {}).get("items") or [])
    items = sorted((own + legacy_items), key=lambda x: float(x.get("epoch") or 0), reverse=True)[:300]
    counts = {p: sum(1 for x in items if x.get("priority") == p) for p in ("P0", "P1", "P2", "P3")}
    return {
        "status": "READY",
        "version": VERSION,
        "new": fresh,
        "items": items,
        "counts": counts,
        "server_side_continuous": True,
        "delivery": {
            "in_app": True,
            "browser_notification_when_enabled": True,
            "closed_app_web_push": False,
        },
        "policy": "P0/P1 are urgent attention states, P2/P3 are earlier discovery states. Priorities are not profit probabilities.",
    }


def alert_snapshot(since_epoch: float = 0.0, limit: int = 200) -> dict:
    with _LOCK:
        own = list(_V74_ALERT_HISTORY)
    cutoff = _f(since_epoch, 0.0) or 0.0
    items = [x for x in own if float(x.get("epoch") or 0) > cutoff]
    items.sort(key=lambda x: float(x.get("epoch") or 0))
    items = items[-max(1, min(int(limit), 500)):]
    latest = max([float(x.get("epoch") or 0) for x in own], default=0.0)
    return {
        "version": VERSION,
        "status": "READY",
        "items": items,
        "latest_epoch": latest,
        "counts": {p: sum(1 for x in own[-500:] if x.get("priority") == p) for p in ("P0", "P1", "P2", "P3")},
        "server_side_continuous": True,
        "read_only": True,
    }


def _hero_blockers(underlying: dict, strike_pack: dict, plan: dict, chart: Optional[dict]) -> List[str]:
    blockers: List[str] = []
    age = _quote_age(underlying)
    if age is not None and age > 10:
        blockers.append("DATA STALE")
    winner = (strike_pack or {}).get("winner") or {}
    scores = winner.get("scores") or {}
    spread = _f(winner.get("spread_pct"), _f((plan.get("evidence") or {}).get("spread_pct")))
    liquidity = _f(winner.get("liquidity"), _f(scores.get("liquidity"), _f((plan.get("evidence") or {}).get("liquidity"))))
    premium_response = _f(scores.get("premium_response"), _f((plan.get("evidence") or {}).get("premium_response")))
    theta = _f(scores.get("theta_risk"), _f(winner.get("theta_risk")))
    if spread is not None and spread > 2.5:
        blockers.append("SPREAD WIDE")
    if liquidity is not None and liquidity < 55:
        blockers.append("LIQUIDITY POOR")
    if premium_response is not None and premium_response < 48:
        blockers.append("PREMIUM NOT RESPONDING")
    if underlying.get("sector_conflict"):
        blockers.append("SECTOR CONFLICT")
    if underlying.get("oi_conflict"):
        blockers.append("OI CONFLICT")
    if underlying.get("false_breakout") or (strike_pack or {}).get("false_breakout"):
        blockers.append("FALSE-BREAK EVIDENCE")
    if underlying.get("late_entry") or str(underlying.get("move_quality") or "").upper() in ("LATE", "CROWDED", "EXHAUSTED"):
        blockers.append("LATE/CROWDED ENTRY")
    if underlying.get("vix_shock") or str(underlying.get("vix_regime") or "").upper() in ("SHOCK", "PANIC"):
        blockers.append("VIX SHOCK")
    entry = (plan.get("entry") or {}).get("ideal")
    sl = (plan.get("risk") or {}).get("premium_sl")
    t1 = (plan.get("targets") or {}).get("t1")
    if all(_f(x) is not None for x in (entry, sl, t1)):
        risk = abs(_f(entry) - _f(sl))
        reward = abs(_f(t1) - _f(entry))
        if risk <= 0 or reward / risk < 1.1:
            blockers.append("POOR R:R")
    if theta is not None and theta >= 75 and _expiry_mode(underlying):
        blockers.append("EXPIRY THETA DANGER")
    if underlying.get("mtf_conflict") or (isinstance(chart, dict) and chart.get("mtf_conflict")):
        blockers.append("MULTI-TIMEFRAME CONFLICT")
    return blockers


def hero5_execution_plan(symbol: str, underlying: dict, strike_pack: dict, chart: Optional[dict] = None) -> dict:
    base = hero_execution_plan_v73(symbol, underlying, strike_pack, chart)
    winner = (strike_pack or {}).get("winner") or {}
    blockers = _hero_blockers(underlying, strike_pack, base, chart)
    ready = base.get("status") == "READY" and not blockers
    side = str(base.get("side") or winner.get("side") or "WAIT").upper()
    action = "CALL" if side == "CE" and ready else "PUT" if side == "PE" and ready else "WAIT"
    ev = base.get("evidence") or {}
    liquidity = _f(ev.get("liquidity"), _f(winner.get("liquidity")))
    spread = _f(winner.get("spread_pct"))
    lgrade = "A" if liquidity is not None and liquidity >= 80 and (spread is None or spread <= 1.0) else "B" if liquidity is not None and liquidity >= 65 else "C" if liquidity is not None else "UNAVAILABLE"
    sc = seven_scouts(underlying)
    opt = sc.get("scouts", {}).get("options", {})
    order = sc.get("scouts", {}).get("order_flow", {})
    oi = sc.get("scouts", {}).get("oi", {})
    pattern = sc.get("scouts", {}).get("pattern", {})
    sector = sc.get("scouts", {}).get("sector", {})
    entry = base.get("entry") or {}
    risk = base.get("risk") or {}
    targets = base.get("targets") or {}
    why_now = [
        f"{name.replace('_',' ').title()} scout {info.get('score')}" for name, info in sc.get("scouts", {}).items()
        if info.get("status") == "READY" and (_f(info.get("score"), 0) or 0) >= 65
    ][:6]
    if not why_now:
        why_now = ["Insufficient multi-scout confirmation; WAIT remains valid."]
    why_strike = []
    if winner:
        if winner.get("strike") is not None:
            why_strike.append(f"Selected strike {winner.get('strike')} from current strike intelligence.")
        if liquidity is not None:
            why_strike.append(f"Liquidity evidence {round(liquidity,1)} / 100.")
        if spread is not None:
            why_strike.append(f"Observed spread {round(spread,3)}%.")
    what_changed = list((underlying.get("what_changed") or [])) if isinstance(underlying.get("what_changed"), list) else []
    hm = sc.get("history_metrics") or {}
    if _f(hm.get("price_acceleration")) is not None:
        what_changed.append(f"Price acceleration {round(_f(hm.get('price_acceleration')) or 0,3)} pct-units.")
    invalidates = list(blockers)
    underlying_inv = risk.get("underlying_invalidation")
    if underlying_inv is not None:
        invalidates.append(f"Underlying invalidation {underlying_inv}")
    if risk.get("premium_sl") is not None:
        invalidates.append(f"Premium SL {risk.get('premium_sl')}")
    return {
        "version": VERSION,
        "status": "READY" if ready else "BLOCKED",
        "action": action,
        "symbol": symbol.upper(),
        "expiry": base.get("expiry") or winner.get("expiry") or strike_pack.get("expiry"),
        "strike": base.get("strike") or winner.get("strike"),
        "premium": base.get("premium") or winner.get("premium"),
        "entry_low": entry.get("low"), "ideal_entry": entry.get("ideal"), "entry_high": entry.get("high"),
        "do_not_chase": entry.get("do_not_chase_above"),
        "sl": risk.get("premium_sl"), "structural_sl": risk.get("underlying_invalidation"), "time_stop_min": risk.get("time_stop_min"),
        "t1": targets.get("t1"), "t2": targets.get("t2"), "t3": targets.get("t3"), "extended_target": targets.get("extended"),
        "trailing_rule": "After T1, trail only while OI + premium response + depth + underlying structure remain supportive; never widen risk.",
        "re_entry": "Only evidence-supported breakout retest / VWAP reclaim / demand retest / supply flip / continuation; never average down.",
        "liquidity_grade": lgrade, "liquidity_score": liquidity, "spread_pct": spread,
        "depth": order, "oi_state": oi, "iv_state": {"iv": opt.get("iv"), "gamma": opt.get("gamma")},
        "vix_regime": underlying.get("vix_regime"), "sector_strength": sector,
        "pattern": pattern, "supply_demand": underlying.get("supply_demand") or {"supply": underlying.get("supply_zone"), "demand": underlying.get("demand_zone")},
        "break_pressure": underlying.get("break_pressure"), "premium_response": opt.get("premium_response") or ev.get("premium_response"),
        "why_now": why_now, "why_this_strike": why_strike or ["No qualifying strike evidence."],
        "what_changed": what_changed or ["No change telemetry supplied."],
        "what_invalidates": invalidates or ["Loss of multi-scout alignment or breach of structural risk level."],
        "blocked_by": blockers,
        "base_v73_plan": base,
        "read_only": True,
        "execution_enabled": False,
        "policy": "Exact levels are decision-support values, not guaranteed fills/returns. Trade qualification is stricter than opportunity discovery.",
    }



def _rr(entry: Any, stop: Any, target: Any) -> Optional[float]:
    e, s, t = _f(entry), _f(stop), _f(target)
    if e is None or s is None or t is None:
        return None
    risk = abs(e - s)
    if risk <= 1e-9:
        return None
    return abs(t - e) / risk


def call_engine_plan(symbol: str, underlying: dict, strike_pack: dict, chart: Optional[dict] = None, now_epoch: Optional[float] = None) -> dict:
    """Strict, auditable call card built on top of Hero 5.0.

    CALL QUALITY is an evidence score, not a probability of profit. WAIT is a first-
    class output. No order is sent to a broker.
    """
    now_epoch = float(now_epoch or time.time())
    hero = hero5_execution_plan(symbol, underlying, strike_pack, chart)
    sc = seven_scouts(underlying)
    ready_count = int(sc.get("ready_count") or 0)
    base = hero.get("base_v73_plan") or {}
    evidence = base.get("evidence") or {}
    hero_score = _f(evidence.get("hero_score"), _f((strike_pack.get("winner") or {}).get("score"), 0.0)) or 0.0
    underlying_score = _f(evidence.get("underlying_score"), _f(underlying.get("pre_move_score"), _f(underlying.get("score"), 0.0))) or 0.0
    liquidity = _f(hero.get("liquidity_score"), _f(evidence.get("liquidity")))
    spread = _f(hero.get("spread_pct"))
    age = _quote_age(underlying)
    rr1 = _rr(hero.get("ideal_entry"), hero.get("sl"), hero.get("t1"))
    rr2 = _rr(hero.get("ideal_entry"), hero.get("sl"), hero.get("t2"))
    rr3 = _rr(hero.get("ideal_entry"), hero.get("sl"), hero.get("t3"))

    liquidity_component = 50.0 if liquidity is None else _clamp(liquidity)
    spread_component = 55.0 if spread is None else _clamp(100 - max(0.0, spread - 0.25) * 28)
    freshness_component = 75.0 if age is None else _clamp(100 - max(0.0, age - 1.5) * 10)
    scout_component = _clamp(ready_count / 7.0 * 100)
    rr_component = 45.0 if rr1 is None else _clamp(rr1 / 2.0 * 100)
    quality = (
        hero_score * .24 + underlying_score * .20 + liquidity_component * .14 +
        spread_component * .10 + freshness_component * .10 + scout_component * .12 + rr_component * .10
    )
    blockers = list(hero.get("blocked_by") or [])
    if blockers:
        quality -= min(38.0, 8.0 * len(blockers))
    quality = round(_clamp(quality), 1)

    side = str((base.get("side") or (strike_pack.get("winner") or {}).get("side") or "WAIT")).upper()
    raw_action = "BUY CE" if side == "CE" else "BUY PE" if side == "PE" else "WAIT"
    stage = str(underlying.get("pre_move_stage") or underlying.get("stage") or "DISCOVERY").upper()
    stage_rank = {x: i for i, x in enumerate(LIFECYCLE)}.get(stage, 0)
    min_ready_rank = {x: i for i, x in enumerate(LIFECYCLE)}.get("TRIGGER NEAR", 5)

    gates = {
        "hero_ready": hero.get("status") == "READY" and raw_action != "WAIT",
        "fresh": age is None or age <= 10,
        "liquid": liquidity is not None and liquidity >= 60,
        "spread_ok": spread is not None and spread <= 2.0,
        "scout_coverage": ready_count >= 4,
        "rr_ok": rr1 is not None and rr1 >= 1.15,
        "not_late": not bool(underlying.get("late_entry")) and "LATE/CROWDED ENTRY" not in blockers,
        "stage_ready": stage_rank >= min_ready_rank,
    }
    hard_pass = all(gates[k] for k in ("hero_ready", "fresh", "liquid", "spread_ok", "scout_coverage", "rr_ok", "not_late"))
    if hard_pass and gates["stage_ready"] and quality >= 72:
        status = "READY"
        action = raw_action
    elif raw_action != "WAIT" and quality >= 58 and gates["fresh"] and gates["not_late"]:
        status = "ARMING"
        action = "WAIT"
    else:
        status = "WAIT"
        action = "WAIT"

    current_premium = _f(hero.get("premium"))
    chase = _f(hero.get("do_not_chase"))
    if status == "READY" and current_premium is not None and chase is not None and current_premium > chase:
        status, action = "DO NOT CHASE", "WAIT"

    valid_for = 150 if stage in ("TRIGGER READY", "HERO", "ENTRY ACTIVE") else 240 if stage == "TRIGGER NEAR" else 360
    reasons = list(hero.get("why_now") or [])[:6]
    if status != "READY" and blockers:
        reasons = [f"Blocked: {x}" for x in blockers[:4]] + reasons[:2]

    return {
        "version": VERSION,
        "engine": "CALL ENGINE 1.0",
        "symbol": symbol.upper(),
        "status": status,
        "action": action,
        "underlying_action": "BUY" if side == "CE" else "SELL" if side == "PE" else "WAIT",
        "underlying_side": side,
        "stage": stage,
        "call_quality": quality,
        "quality_is_probability": False,
        "entry_zone": {"low": hero.get("entry_low"), "ideal": hero.get("ideal_entry"), "high": hero.get("entry_high")},
        "entry_ladder": {"aggressive": hero.get("entry_low"), "ideal": hero.get("ideal_entry"), "confirmation": hero.get("entry_high")},
        "underlying_trigger": ((base.get("entry") or {}).get("underlying_trigger")),
        "sl": hero.get("sl"),
        "structural_sl": hero.get("structural_sl"),
        "targets": {"t1": hero.get("t1"), "t2": hero.get("t2"), "t3": hero.get("t3"), "extended": hero.get("extended_target")},
        "risk_reward": {"t1": round(rr1, 2) if rr1 is not None else None, "t2": round(rr2, 2) if rr2 is not None else None, "t3": round(rr3, 2) if rr3 is not None else None},
        "strike": hero.get("strike"), "expiry": hero.get("expiry"), "premium": hero.get("premium"),
        "do_not_chase_above": hero.get("do_not_chase"),
        "time_stop_min": hero.get("time_stop_min"),
        "valid_from_epoch": now_epoch,
        "valid_until_epoch": now_epoch + valid_for,
        "valid_for_sec": valid_for,
        "re_entry": hero.get("re_entry"),
        "trailing_rule": hero.get("trailing_rule"),
        "quality_gate": gates,
        "blocked_by": blockers,
        "why_now": reasons,
        "why_this_strike": hero.get("why_this_strike") or [],
        "what_changed": hero.get("what_changed") or [],
        "what_invalidates": hero.get("what_invalidates") or [],
        "liquidity_grade": hero.get("liquidity_grade"),
        "liquidity_score": liquidity,
        "spread_pct": spread,
        "scout_coverage": f"{ready_count}/7",
        "model_tracking_only": True,
        "read_only": True,
        "execution_enabled": False,
        "policy": "Actionable only after strict evidence gates. CALL QUALITY is not a win probability. WAIT and DO NOT CHASE are valid outputs; no broker order is placed.",
    }


def _call_key(plan: dict) -> str:
    strike = plan.get("strike") if plan.get("strike") is not None else "NA"
    direction = str(plan.get("underlying_side") or plan.get("action") or "WAIT")
    return f"{plan.get('symbol')}|{direction}|{strike}|{plan.get('expiry') or 'NA'}"


def _persist_call_row(state: dict) -> None:
    try:
        sql = (
            "INSERT INTO v74_calls("
            "call_id,epoch,updated_epoch,symbol,action,status,entry_low,ideal_entry,entry_high,sl,structural_sl,"
            "t1,t2,t3,extended_target,premium,quality_score,rr_t1,stage,expiry,strike,result,max_favorable_pct,max_adverse_pct,payload_json"
            ") VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) "
            "ON CONFLICT(call_id) DO UPDATE SET "
            "updated_epoch=excluded.updated_epoch,status=excluded.status,premium=excluded.premium,result=excluded.result,"
            "max_favorable_pct=excluded.max_favorable_pct,max_adverse_pct=excluded.max_adverse_pct,payload_json=excluded.payload_json"
        )
        with _call_db() as c:
            c.execute(
                sql,
                (
                    state.get("call_id"), state.get("epoch"), state.get("updated_epoch"), state.get("symbol"), state.get("action"), state.get("status"),
                    _f(state.get("entry_low")), _f(state.get("ideal_entry")), _f(state.get("entry_high")), _f(state.get("sl")), _f(state.get("structural_sl")),
                    _f(state.get("t1")), _f(state.get("t2")), _f(state.get("t3")), _f(state.get("extended_target")), _f(state.get("premium")), _f(state.get("quality_score")), _f(state.get("rr_t1")),
                    state.get("stage"), state.get("expiry"), _f(state.get("strike")), state.get("result"), _f(state.get("max_favorable_pct"),0.0) or 0.0, _f(state.get("max_adverse_pct"),0.0) or 0.0,
                    json.dumps(state, default=str, separators=(",", ":")),
                ),
            )
    except Exception:
        # Journal persistence must never break live scanning.
        return


def track_call_plan(plan: dict) -> dict:
    """Track model-call lifecycle without assuming the user actually entered a trade."""
    now = time.time()
    symbol = str(plan.get("symbol") or "")
    if not symbol:
        return plan
    key = _call_key(plan)
    with _LOCK:
        state = _CALL_STATE.get(key)
        if state is None and plan.get("status") == "READY" and plan.get("action") in ("BUY CE", "BUY PE"):
            call_id = f"V742-{symbol}-{int(now*1000)}"
            state = {
                "call_id": call_id, "epoch": now, "updated_epoch": now, "symbol": symbol,
                "action": plan.get("action"), "status": "READY", "result": None,
                "entry_low": (plan.get("entry_zone") or {}).get("low"), "ideal_entry": (plan.get("entry_zone") or {}).get("ideal"), "entry_high": (plan.get("entry_zone") or {}).get("high"),
                "sl": plan.get("sl"), "structural_sl": plan.get("structural_sl"),
                "t1": (plan.get("targets") or {}).get("t1"), "t2": (plan.get("targets") or {}).get("t2"), "t3": (plan.get("targets") or {}).get("t3"), "extended_target": (plan.get("targets") or {}).get("extended"),
                "premium": plan.get("premium"), "quality_score": plan.get("call_quality"), "rr_t1": (plan.get("risk_reward") or {}).get("t1"),
                "stage": plan.get("stage"), "expiry": plan.get("expiry"), "strike": plan.get("strike"),
                "valid_until_epoch": plan.get("valid_until_epoch"), "max_favorable_pct": 0.0, "max_adverse_pct": 0.0,
                "model_tracking_only": True,
            }
            _CALL_STATE[key] = state
        elif state is not None:
            state["updated_epoch"] = now
            px = _f(plan.get("premium"))
            entry = _f(state.get("ideal_entry"))
            if px is not None and entry:
                excursion = (px - entry) / abs(entry) * 100.0
                state["max_favorable_pct"] = max(_f(state.get("max_favorable_pct"),0.0) or 0.0, excursion)
                state["max_adverse_pct"] = min(_f(state.get("max_adverse_pct"),0.0) or 0.0, excursion)
            state["premium"] = plan.get("premium")
            if px is not None:
                if _f(state.get("t3")) is not None and px >= _f(state.get("t3")):
                    state["status"] = state["result"] = "T3 HIT"
                elif _f(state.get("t2")) is not None and px >= _f(state.get("t2")):
                    state["status"] = state["result"] = "T2 HIT"
                elif _f(state.get("t1")) is not None and px >= _f(state.get("t1")):
                    state["status"] = state["result"] = "T1 HIT"
                elif _f(state.get("sl")) is not None and px <= _f(state.get("sl")):
                    state["status"] = state["result"] = "SL HIT"
                else:
                    state["status"] = "ACTIVE"
            if not state.get("result") and _f(state.get("valid_until_epoch")) is not None and now > _f(state.get("valid_until_epoch")):
                state["status"] = state["result"] = "EXPIRED"
        current = dict(state) if state is not None else None
    if current:
        _persist_call_row(current)
        plan = {**plan, "model_call_id": current.get("call_id"), "model_call_state": current.get("status"), "model_call_result": current.get("result")}
    return plan


def emit_call_alert(plan: dict, ttl: int = 60) -> Optional[dict]:
    status = str(plan.get("status") or "WAIT")
    if status not in ("READY", "ARMING"):
        return None
    quality = _f(plan.get("call_quality"), 0.0) or 0.0
    priority = "P0" if status == "READY" and quality >= 82 else "P1" if status == "READY" else "P2"
    sym = str(plan.get("symbol") or "")
    action = str(plan.get("action") or "WAIT")
    call_id = str(plan.get("model_call_id") or "")
    sig = f"CALL|{call_id or sym}|{action}|{plan.get('strike')}|{status}"
    now = time.time()
    with _LOCK:
        if now - _V74_ALERT_LAST_SIG.get(sig, 0.0) < max(15, int(ttl)):
            return None
        _V74_ALERT_LAST_SIG[sig] = now
        ez = plan.get("entry_zone") or {}
        targets = plan.get("targets") or {}
        item = {
            "id": f"V742-CALL-{int(now*1000)}-{len(_V74_ALERT_HISTORY)}",
            "epoch": now, "priority": priority, "kind": "CALL_ENGINE", "symbol": sym,
            "stage": plan.get("stage"), "reason": f"{action} | Entry {ez.get('low')}-{ez.get('high')} | SL {plan.get('sl')} | T1 {targets.get('t1')}",
            "action": action, "call_quality": quality, "strike": plan.get("strike"), "expiry": plan.get("expiry"),
            "entry_zone": ez, "sl": plan.get("sl"), "t1": targets.get("t1"), "t2": targets.get("t2"), "t3": targets.get("t3"),
            "model_call_id": plan.get("model_call_id"), "read_only": True,
        }
        _V74_ALERT_HISTORY.append(item)
        return item


def active_call_symbols(limit: int = 100) -> List[str]:
    symbols = []
    with _LOCK:
        for st in _CALL_STATE.values():
            if not st.get("result") and st.get("symbol"):
                symbols.append(str(st.get("symbol")).upper())
    try:
        with _call_db() as c:
            rows = c.execute("SELECT DISTINCT symbol FROM v74_calls WHERE result IS NULL ORDER BY updated_epoch DESC LIMIT ?", (max(1,min(int(limit),500)),)).fetchall()
            symbols.extend(str(r["symbol"]).upper() for r in rows if r["symbol"])
    except Exception:
        pass
    return list(dict.fromkeys(symbols))[:max(1,min(int(limit),500))]


def call_journal(limit: int = 100) -> dict:
    rows = []
    storage_error = None
    try:
        with _call_db() as c:
            got = c.execute("SELECT * FROM v74_calls ORDER BY epoch DESC LIMIT ?", (max(1, min(int(limit), 1000)),)).fetchall()
            for r in got:
                x = dict(r)
                try:
                    x["payload"] = json.loads(x.pop("payload_json") or "{}")
                except Exception:
                    x["payload"] = {}
                rows.append(x)
    except Exception as exc:
        storage_error = str(exc)[:180]
    resolved = [r for r in rows if r.get("result") in ("T1 HIT","T2 HIT","T3 HIT","SL HIT","EXPIRED")]
    wins = [r for r in resolved if str(r.get("result") or "").startswith("T")]
    sls = [r for r in resolved if r.get("result") == "SL HIT"]
    def window_stats(n: int) -> dict:
        sample = resolved[:n]
        if not sample:
            return {"sample_size":0,"target_hit_pct":None,"sl_hit_pct":None,"median_mfe_pct":None,"median_mae_pct":None,"average_rr_t1":None}
        target = [r for r in sample if str(r.get("result") or "").startswith("T")]
        stop = [r for r in sample if r.get("result") == "SL HIT"]
        mfes=[_f(r.get("max_favorable_pct"),0.0) or 0.0 for r in sample]
        maes=[_f(r.get("max_adverse_pct"),0.0) or 0.0 for r in sample]
        rrs=[_f(r.get("rr_t1")) for r in sample if _f(r.get("rr_t1")) is not None]
        return {"sample_size":len(sample),"target_hit_pct":round(100*len(target)/len(sample),1),"sl_hit_pct":round(100*len(stop)/len(sample),1),"median_mfe_pct":round(statistics.median(mfes),2),"median_mae_pct":round(statistics.median(maes),2),"average_rr_t1":round(statistics.fmean(rrs),2) if rrs else None}
    return {
        "version": VERSION, "rows": rows, "resolved": len(resolved), "target_hits": len(wins), "sl_hits": len(sls),
        "last20": window_stats(20), "last50": window_stats(50), "last100": window_stats(100),
        "storage": {"path": str(V74_DB_PATH), "error": storage_error, "deploy_durable_requires_persistent_disk": True},
        "accuracy_policy": "Observed resolved model calls only. Statistics are historical observations, not guarantees of future accuracy.",
        "read_only": True,
    }


def shadow_comparator(candidates: List[dict], v73: dict) -> dict:
    """Same-snapshot V74-vs-V73/V72 stage comparator; not an outcome forecast."""
    v73_rows = (((v73.get("base_v72") or {}).get("pre_move_rows")) or [])
    m73 = {str(x.get("symbol") or "").upper(): x for x in v73_rows if x.get("symbol")}
    rank = {x:i for i,x in enumerate(LIFECYCLE)}
    aliases = {"SCANNING":"DISCOVERY","WATCH":"EARLY CLUE","EARLY MOVER":"EARLY CLUE","HERO READY":"HERO","HERO ACTIVE":"ENTRY ACTIVE"}
    ahead = same = behind = 0
    rows=[]
    for c in candidates:
        sym=str(c.get("symbol") or "")
        old=m73.get(sym) or {}
        s74=str(c.get("stage") or "DISCOVERY").upper()
        s73=str(old.get("pre_move_stage") or old.get("stage") or "SCANNING").upper()
        s73=aliases.get(s73,s73)
        d=rank.get(s74,0)-rank.get(s73,0)
        if d>0: ahead+=1
        elif d<0: behind+=1
        else: same+=1
        if abs(d)>=1:
            rows.append({"symbol":sym,"v74_stage":s74,"v73_stage":s73,"stage_delta":d,"v74_score":c.get("score"),"v73_score":old.get("pre_move_score") or old.get("score")})
    summary={"epoch":time.time(),"v74_ahead":ahead,"same":same,"v74_behind":behind,"compared":ahead+same+behind}
    with _LOCK:
        _SHADOW_HISTORY.append(summary)
    rows.sort(key=lambda x:abs(int(x.get("stage_delta") or 0)),reverse=True)
    return {**summary,"largest_differences":rows[:30],"policy":"Stage comparison on the same snapshot. It does not by itself prove better trading outcomes.","read_only":True}


def hot_lane_candidates(candidates: List[dict], limit: int = 30) -> List[dict]:
    rank={x:i for i,x in enumerate(LIFECYCLE)}
    out=[]
    for c in candidates:
        price=_scout(c,"price")
        vel=(price.get("velocity") or {})
        burst=max([abs(_f(vel.get(k),0.0) or 0.0) for k in ("15s","30s","60s")],default=0.0)
        if rank.get(str(c.get("stage") or "DISCOVERY"),0)>=rank.get("ARMING",4) or burst>=0.18 or (_f(c.get("score"),0) or 0)>=67:
            out.append({**c,"hot_burst_pct":round(burst,3)})
    out.sort(key=lambda x:(rank.get(str(x.get("stage") or "DISCOVERY"),0),_f(x.get("score"),0) or 0,_f(x.get("hot_burst_pct"),0) or 0),reverse=True)
    return out[:max(1,min(int(limit),100))]



def _scout(candidate: dict, name: str) -> dict:
    return (((candidate.get("scout_pack") or {}).get("scouts") or {}).get(name) or {})


def _scout_score(candidate: dict, name: str) -> float:
    val = _f(_scout(candidate, name).get("score"))
    return val if val is not None else -1.0


def _workspace_payload(
    snapshot: dict,
    v73: dict,
    candidates: List[dict],
    coverage: dict,
    session: dict,
    alerts: dict,
    misses: dict,
    performance: dict,
    shadow: Optional[dict] = None,
    journal: Optional[dict] = None,
) -> dict:
    """Evidence-specific datasets for the compact nine-workspace UI."""
    rank = {x: i for i, x in enumerate(LIFECYCLE)}
    gainers = sorted((x for x in candidates if (_f(x.get("change_pct"), 0) or 0) > 0), key=lambda x: _f(x.get("change_pct"), 0) or 0, reverse=True)[:30]
    losers = sorted((x for x in candidates if (_f(x.get("change_pct"), 0) or 0) < 0), key=lambda x: _f(x.get("change_pct"), 0) or 0)[:30]
    fast = sorted(candidates, key=lambda x: (_scout_score(x, "price"), abs(_f(x.get("change_pct"), 0) or 0)), reverse=True)[:40]
    hot = hot_lane_candidates(candidates, 40)
    adv = sum(1 for x in candidates if (_f(x.get("change_pct"), 0) or 0) > 0)
    dec = sum(1 for x in candidates if (_f(x.get("change_pct"), 0) or 0) < 0)
    flat = max(0, len(candidates) - adv - dec)
    changes = [_f(x.get("change_pct")) for x in candidates if _f(x.get("change_pct")) is not None]

    sector_groups: Dict[str, List[dict]] = defaultdict(list)
    for x in candidates:
        sector = str(x.get("sector") or "").strip()
        if sector and sector.upper() not in ("N/A", "NA", "NONE", "UNKNOWN"):
            sector_groups[sector].append(x)
    sectors = []
    for sector, members in sector_groups.items():
        ch = [_f(x.get("change_pct"), 0) or 0 for x in members]
        scores = [_f(x.get("score"), 0) or 0 for x in members]
        leader = max(members, key=lambda x: (_f(x.get("score"), 0) or 0, _f(x.get("change_pct"), 0) or 0))
        sectors.append({
            "sector": sector, "symbols": len(members),
            "advancers": sum(1 for v in ch if v > 0), "decliners": sum(1 for v in ch if v < 0),
            "avg_change_pct": round(statistics.fmean(ch), 3) if ch else None,
            "avg_opportunity_score": round(statistics.fmean(scores), 1) if scores else None,
            "leader": leader.get("symbol"), "leader_score": leader.get("score"),
            "leader_change_pct": leader.get("change_pct"),
            "ignition_count": sum(1 for x in members if bool(_scout(x, "sector").get("ignition"))),
        })
    sectors.sort(key=lambda x: (x.get("avg_opportunity_score") or 0, abs(x.get("avg_change_pct") or 0)), reverse=True)

    early = [x for x in candidates if rank.get(str(x.get("stage") or "DISCOVERY"), 0) in (1, 2, 3, 4)]
    trigger = [x for x in candidates if str(x.get("stage") or "") in ("TRIGGER NEAR", "TRIGGER READY", "HERO", "ENTRY ACTIVE")]
    breakouts = [x for x in candidates if x.get("move_class") == "BREAKOUT MOVE" or bool(_scout(x, "pattern").get("breakout"))]
    reversals = [x for x in candidates if x.get("move_class") == "REVERSAL MOVE" or bool(_scout(x, "pattern").get("reversal"))]
    reentry = [x for x in candidates if x.get("second_chance")]

    derivatives, flow, technical = [], [], []
    for x in candidates:
        oi, opt = _scout(x, "oi"), _scout(x, "options")
        vol, order, pattern = _scout(x, "volume"), _scout(x, "order_flow"), _scout(x, "pattern")
        if oi.get("status") == "READY" or opt.get("status") == "READY":
            derivatives.append({
                "symbol": x.get("symbol"), "ltp": x.get("ltp"), "change_pct": x.get("change_pct"), "stage": x.get("stage"),
                "oi_score": oi.get("score"), "oi_state": oi.get("state"), "delta_oi_pct": oi.get("delta_oi_pct"), "oi_velocity": oi.get("oi_velocity"),
                "option_score": opt.get("score"), "premium_response": opt.get("premium_response"), "iv": opt.get("iv"), "gamma": opt.get("gamma"),
            })
        if vol.get("status") == "READY" or order.get("status") == "READY":
            flow.append({
                "symbol": x.get("symbol"), "stage": x.get("stage"), "change_pct": x.get("change_pct"),
                "volume_score": vol.get("score"), "rvol": vol.get("rvol"), "volume_state": vol.get("state"),
                "order_flow_score": order.get("score"), "pressure": order.get("pressure"), "spread_pct": order.get("spread_pct"),
                "bias": order.get("bias"), "absorption": order.get("absorption"), "liquidity_vacuum": order.get("liquidity_vacuum"),
            })
        if pattern.get("status") == "READY" or x.get("supply_demand") or x.get("pattern"):
            technical.append({
                "symbol": x.get("symbol"), "stage": x.get("stage"), "change_pct": x.get("change_pct"),
                "pattern": pattern.get("pattern") or x.get("pattern"), "pattern_score": pattern.get("score"),
                "breakout": pattern.get("breakout"), "reversal": pattern.get("reversal"), "compression": pattern.get("compression"),
                "supply_demand": x.get("supply_demand"), "break_pressure": x.get("break_pressure"),
            })
    derivatives.sort(key=lambda x: max((_f(x.get("oi_score")) if _f(x.get("oi_score")) is not None else -1), (_f(x.get("option_score")) if _f(x.get("option_score")) is not None else -1)), reverse=True)
    flow.sort(key=lambda x: max((_f(x.get("volume_score")) if _f(x.get("volume_score")) is not None else -1), (_f(x.get("order_flow_score")) if _f(x.get("order_flow_score")) is not None else -1)), reverse=True)
    technical.sort(key=lambda x: (_f(x.get("pattern_score")) if _f(x.get("pattern_score")) is not None else -1), reverse=True)

    market = {
        "breadth": {"advancers": adv, "decliners": dec, "unchanged": flat, "advance_decline_ratio": round(adv / dec, 3) if dec else ("ADVANCE_ONLY" if adv else None), "average_change_pct": round(statistics.fmean(changes), 3) if changes else None},
        "active_underlying": snapshot.get("active_underlying"), "spot": snapshot.get("spot"),
        "index_brain": snapshot.get("index_brain"), "gainers": gainers, "losers": losers, "fast_movers": fast,
        "sectors": sectors, "sector_count": len(sectors),
    }
    opportunities = {
        "hot_lane": hot,
        "early_build": sorted(early, key=lambda x: _f(x.get("score"), 0) or 0, reverse=True)[:80],
        "trigger_queue": trigger[:60], "breakouts": breakouts[:40], "reversals": reversals[:40],
        "circuits": ((v73.get("circuit_hunter") or {}).get("candidates") or [])[:40],
    }
    calls = {
        "hero_ready": [x for x in candidates if str(x.get("stage") or "") in ("TRIGGER READY", "HERO", "ENTRY ACTIVE")][:40],
        "reentry": reentry[:60], "supply_demand": [x for x in candidates if x.get("supply_demand")][:50],
        "journal_stats": journal or {},
        "policy": "CALL ENGINE is stricter than discovery. WAIT and DO NOT CHASE are valid outputs; broker orders remain disabled.",
    }
    flow_technical = {"flow": flow[:100], "technical": technical[:100], "chart": "verified candle endpoint"}
    journal_audit = {"miss_killer": misses, "performance": performance, "replay": "durable V72/V73 timeline", "shadow": shadow or {}, "call_journal": journal or {}}
    payload = {
        "market": market,
        "opportunities": opportunities,
        "calls": calls,
        "derivatives": {"rows": derivatives[:100], "expiry_mode": bool(session.get("expiry_mode")), "session_brain": session, "option_chain": "verified provider endpoint"},
        "flow-technical": flow_technical,
        "alerts": alerts,
        "journal-audit": journal_audit,
        "system": {"coverage": coverage, "data_quality": v73.get("data_quality"), "session_brain": session},
    }
    # Compatibility aliases for older V74 UI/API consumers.
    payload["sectors"] = {"rows": sectors, "count": len(sectors)}
    payload["execution"] = calls
    payload["flow"] = {"rows": flow[:100]}
    payload["technical"] = {"rows": technical[:100], "chart": "verified candle endpoint"}
    payload["audit"] = journal_audit
    return payload

def build_v74(snapshot: dict, record: bool = True) -> dict:
    t0 = time.perf_counter()
    v73 = build_v73(snapshot, record=record)
    raw_rows = _snapshot_rows(snapshot, v73)
    # First pass session without candidates; second pass uses candidates for ranking.
    sess0 = {"expiry_mode": _expiry_mode(snapshot, v73)}
    candidates = [candidate_from_row(r, sess0) for r in raw_rows]
    candidates.sort(key=lambda x: (x.get("stage") in ("TRIGGER READY", "TRIGGER NEAR", "ARMING"), _f(x.get("score"), 0) or 0), reverse=True)
    sess = session_brain(snapshot, candidates, v73)
    coverage = _coverage(v73, candidates)
    big = [x for x in candidates if x.get("big_move_state") in ("EARLY BUILD", "PRESSURE RISING", "BREAK IMMINENT", "MOVE ACTIVE")]
    big.sort(key=lambda x: (_f(x.get("score"), 0) or 0, abs(_f(x.get("change_pct"), 0) or 0)), reverse=True)
    reentry = [x for x in candidates if x.get("second_chance")]
    alerts = alert_engine_v74(candidates, v73.get("alerts"))
    misses = miss_killer_report()
    performance_intel = performance_intelligence(candidates)
    shadow = shadow_comparator(candidates, v73)
    journal = call_journal(100)
    hot_lane = hot_lane_candidates(candidates, 40)
    workspaces = _workspace_payload(snapshot, v73, candidates, coverage, sess, alerts, misses, performance_intel, shadow=shadow, journal=journal)
    ms = (time.perf_counter() - t0) * 1000.0
    return {
        "version": VERSION,
        "release": RELEASE,
        "name": "POWERHOUSE AI V74.2 — Autonomous Call Intelligence OS",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "read_only": True,
        "execution_enabled": False,
        "mission": "AUTONOMOUS MOVE DISCOVERY + STRICT CALL QUALITY + AUDITABLE ENTRY/SL/TARGETS + ZERO SILENT MISSES",
        "tabs": TAB_ARCHITECTURE,
        "ui_workspaces": WORKSPACE_ARCHITECTURE,
        "workspaces": workspaces,
        "move_classes": MOVE_CLASSES,
        "lifecycle": LIFECYCLE,
        "command": {
            "coverage": coverage,
            "big_move_forming": big[:20],
            "hero_ready": [x for x in candidates if x.get("stage") in ("TRIGGER READY", "HERO", "ENTRY ACTIVE")][:20],
            "re_entry": reentry[:20],
            "session_brain": sess,
            "data_quality": v73.get("data_quality"),
        },
        "coverage": coverage,
        "radar": {"count": len(candidates), "candidates": candidates},
        "big_move_capture_engine": {
            "version": "5.2", "scouts": list(SCOUT_WEIGHTS), "candidates": big[:100],
            "hot_lane": hot_lane,
            "states": ["WATCH", "EARLY BUILD", "PRESSURE RISING", "BREAK IMMINENT", "MOVE ACTIVE"],
        },
        "miss_killer": misses,
        "performance_intelligence": performance_intel,
        "call_journal": journal,
        "shadow_comparison": shadow,
        "hot_lane": hot_lane,
        "session_brain": sess,
        "circuits": v73.get("circuit_hunter"),
        "alerts": alerts,
        "base_v73": v73,
        "performance": {"v74_orchestration_ms": round(ms, 2), "base_v73": v73.get("performance")},
        "truth_policy": [
            "100% movement capture is an engineering coverage target, not a profitability guarantee.",
            "Every observed meaningful move is detected or assigned an explicit miss classification; silent misses are not allowed.",
            "Missing scouts reduce evidence coverage; missing data is never fabricated as neutral or LIVE.",
            "Opportunity discovery stays broad, while CALL ENGINE qualification remains strict; WAIT and DO NOT CHASE are valid outputs.",
            "CALL QUALITY is an evidence score, not a probability of profit or guaranteed accuracy.",
            "All outputs are read-only market intelligence; no automatic broker order placement is enabled.",
        ],
    }


def empty_v74_status(reason: str = "Live market authentication/data unavailable") -> dict:
    return {
        "version": VERSION, "release": RELEASE,
        "name": "POWERHOUSE AI V74.2 — Autonomous Call Intelligence OS",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "read_only": True, "execution_enabled": False,
        "tabs": TAB_ARCHITECTURE,
        "ui_workspaces": WORKSPACE_ARCHITECTURE,
        "workspaces": {"market":{},"opportunities":{},"calls":{},"derivatives":{"rows":[]},"flow-technical":{"flow":[],"technical":[]},"alerts":alert_snapshot(),"journal-audit":{},"system":{},"sectors":{"rows":[],"count":0},"execution":{},"flow":{"rows":[]},"technical":{"rows":[]},"audit":{}},
        "coverage": {"universe_expected": 0, "universe_covered": 0, "fresh_quotes": 0, "symbols_scanned": 0,
                     "meaningful_moves_today": 0, "moves_detected_early": 0, "moves_detected_late": 0,
                     "moves_completely_missed": 0, "average_lead_time_sec": None, "coverage_state": "UNAVAILABLE",
                     "silent_misses_allowed": False},
        "radar": {"count": 0, "candidates": []},
        "big_move_capture_engine": {"version": "5.0", "scouts": list(SCOUT_WEIGHTS), "candidates": []},
        "miss_killer": miss_killer_report(),
        "performance_intelligence": performance_intelligence(),
        "data_status": "UNAVAILABLE", "reason": reason,
        "truth_policy": ["No demo/mock market values are substituted for unavailable LIVE data."],
    }
